### ISSUE TITLE
String elimination/projection functions needed

### ISSUE THREAD

**Issue by kquick** [HarvardPL/formulog#2]
Currently there are 4 `string` manipulation functions (plus `to_string`), but inspection is only supported on the prefix or via regexp.  There are no functions to extract from the string (presumably these would be `i32` char values?) or convert to another form such as a list, so the utility of strings is significantly constrained.  

Suggestions would be `string_sub : string -> 'a -> 'b -> string` where `'a` and `'b` are integer forms to extract a sub-string given an offset and a length, `string_char : string -> i32 -> i32` to extract a single character (from which `string_sub` could be synthesized), or `string_to_list : string -> i32 list`.

**Comment by aaronbembenek** [comment]
Thanks! I've added (cffbdba9f4fbf4758a59c20451bdea823b464a19) these new functions, more fully described in the updated documentation:

- `substring : (string, i32, i32) -> string option`
- `char_at : (string, i32) -> i32 option`
- `string_to_list : string -> i32 list`
- `list_to_string : i32 list -> string`

I've also created a new issue (#8) for supporting character literals like `'a'`.
