### ISSUE TITLE
CSV reference

### ISSUE THREAD

**Issue by kquick** [HarvardPL/formulog#3]
In 01-language-basics, in the section "External input relations", TSV should be defined, and the last paragraph contains a reference  to "CSV" which should be "TSV".  You may also want to emphasize somehow that the example document has tabs and not spaces.

**Comment by aaronbembenek** [comment]
Thanks for pointing this out! I've clarified the documentation (commit 11b6921c2fcd090381a5d8320e54ddb9fefcd711).
