### ISSUE TITLE
Can `int smt` types be used

### ISSUE THREAD

**Issue by kquick** [HarvardPL/formulog#5]
The 04_logical_formulas document section "Integers" describes a set of solver operations on types of `int smt`, but 01_language_basics does not describe `int` as one of the 5 built-in primitive types.  Is there an `int` primitive type, or are these somehow auto-converted to an `i32` or `i64`?

**Comment by aaronbembenek** [comment]
There is not a primitive `int` type: it is possible to construct terms of type `int sym` (an `int`-valued SMT variable) and `int smt` (an `int`-valued SMT formula), but it is not possible to construct a term of type `int`. So, in other words, the type `int` is really just intended to be used in SMT formulas, where it represents a mathematical integer.

There is also no automatic conversion between a term of type `int` and terms of type `i32` or `i64`, although (as of commit a43bbc2dc87c9f26aa4532cf662b19c91e73b0f0) we do provide formula constructors `bv_to_int` and `int_to_bv` that can be used to translate between them in formulas.

If there's demand for it, in the future we could add a primitive `int` type. Unlike `i32` and `i64`, this could be used to represent integers of arbitrary size.
