### ISSUE TITLE
List operations

### ISSUE THREAD

**Issue by kquick** [HarvardPL/formulog#6]
From examples/liquid_types.flg, there appears to be an automatic (builtin?) type of `list`, with pattern matching on `[]` and `::` operations.  These are undocumented as far as I can tell. 

Additionally, `::` appears to be an infix constructor, but there's no discussion of infix operators elsewhere (that I saw, maybe I missed it); is `::` unique or is there a language syntax to declare infix operators or constructors and define precedence and affinity?

What are the semantics of `::`?  Is `X :: Y :: ZList` a valid pattern to match the first two elements of a `list`?

**Comment by aaronbembenek** [comment]
I've updated the documentation to describe list notation:

> Formulog provides special notation for terms of the `list` type. The `cons` constructor can be written using the infix notation `::`; i.e., `X :: Y` is shorthand for `cons(X, Y)`. A list can also be written as a sequence of comma-separated elements between a pair of square brackets. For example, the term `[X, Y, Z]` is shorthand for `cons(X, cons(Y, cons(Z, nil)))`. The term `[]` is `nil`, the empty list.
> 
> Both notations can be used in pattern matching (described below).

There's unfortunately no way currently to define other infix operators or constructors from within a Formulog program.
